[package]
name = "rusty-native"
edition = "2021"
version.workspace = true
authors.workspace = true

[dependencies]
log = { workspace = true }
env_logger = "0.10.0"
pixels = "0.13.0"
anyhow = "1.0.71"
winit = "0.28.6"
gamebaby = { path = "../../", features = ["std"] }
